name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: True
    - name: Restore dependencies
      run: dotnet restore ./src/AutoScrum.sln
    - name: Build
      run: dotnet build ./src/AutoScrum.sln --no-restore
    - name: Test
      run: dotnet test ./src/AutoScrum.sln --no-build --verbosity normal
    - name: Publish
      run: dotnet publish ./src/AutoScrum/AutoScrum.csproj -c Release -o ./dist/ --no-restore
    - name: Azure Static Web Apps Deploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        # Action to perform
        action: 'upload'
        # Directory location of the application source code
        app_location: ./src
        # Required token
        azure_static_web_apps_api_token: ${{ secrets.$AZURE_STATIC_WEB_APPS_API_TOKEN }}
        # Custom command for Oryx to run when building Azure Functions source code
        # api_build_command: # optional
        # Directory location of the Azure Functions source code
        # api_location: # optional
        # Identical in use to output_location
        # app_artifact_location: # optional
        # Directory location of the compiled application code after building
        output_location: ./dist/wwwroot
        # Custom command for Oryx to run when building application source code
        # app_build_command: # optional
        # Token for interacting with the Github repository. Currently used only for commenting on Pull Requests.
        # repo_token: # optional
        # Directory location where the routes.json file can be found in the source code
        # routes_location: # optional
        # Skips the build step for the application source code if set to true.
