name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore ./src/AutoScrum.sln
    - name: Build
      run: dotnet build --no-restore ./src/AutoScrum.sln
    - name: Install Playwright
      shell: pwsh
      run: .\src\AutoScrum.UITests\bin\Debug\net6.0\playwright.ps1 install
    - name: Test
      shell: pwsh
      run: |
        $env:BaseUrl="https://autoscrum.jkdev.me"
        $env:IsGitHubActions="true"
        dotnet test ./src/AutoScrum.sln
